### ISSUE TITLE
ERROR: mmaping file '.../temps-5min.rrd': Invalid argument

### ISSUE THREAD

**Issue by soaringswine** [seren/freenas-temperature-graphing#7]
It has not worked since setup. I've tried deleting the .rrd file, running the command manually with -v, tried creating a blank .rrd file then running command, still all get the error. It produces an empty .rrd file.

```
+ '[' -n 1 ']'
+ echo 'Updating the db: '\''/usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:37:37:37:37:37:37:37:37:35:40:41:37:35:34:32:33'\'''
Updating the db: '/usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:37:37:37:37:37:37:37:37:35:40:41:37:35:34:32:33'
+ /usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:37:37:37:37:37:37:37:37:35:40:41:37:35:34:32:33
ERROR: mmaping file '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': Invalid argument
+ '[' -n 1 ']'
+ echo 'Added data'
Added data
```

**Comment by seren** [comment]
Could you upload the temps5-min.rrd file? Also, when the script runs, it has permissions to write to the file, right?

**Comment by soaringswine** [comment]
It's completely empty, 0 bytes. Yes, all the files are owned by root and the cronjob runs as root.

**Comment by seren** [comment]
OK, I think I found the problem. Thanks for letting me know. Could you delete your rrd file, download the latest version, and try again?

**Comment by soaringswine** [comment]
Done. New error!

```
+ echo 'Updating the db: '\''/usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:29:29:29:29:29:29:29:29:34:39:40:36:34:33:31:31'\'''
Updating the db: '/usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:29:29:29:29:29:29:29:29:34:39:40:36:34:33:31:31'
+ /usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:29:29:29:29:29:29:29:29:34:39:40:36:34:33:31:31
ERROR: opening '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': No such file or directory
+ '[' 1 == 0 ']'
+ echo 'ERROR: Couldn'\''t update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd with the data provided. Running diagnostics...'
ERROR: Couldn't update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd with the data provided. Running diagnostics...
+ func_debug_setup
+ echo 'Testing file permissions...'
Testing file permissions...
+ func_test_writable /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd
+ '[' -e /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd ']'
+ echo 'Datafile '\''/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd'\'' doesn'\''t exist'
Datafile '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd' doesn't exist
+ return 1
+ func_debug_setup_return_test 1
+ '[' 1 == 0 ']'
+ echo 'Test failed (returned 1)'
Test failed (returned 1)
+ exit 1
```
Tried touch /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd and then running it again:

```
+ echo 'Updating the db: '\''/usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:29:29:29:29:29:29:29:29:34:39:40:36:34:33:31:31'\'''
Updating the db: '/usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:29:29:29:29:29:29:29:29:34:39:40:36:34:33:31:31'
+ /usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:29:29:29:29:29:29:29:29:34:39:40:36:34:33:31:31
ERROR: mmaping file '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': Invalid argument
+ '[' 1 == 0 ']'
+ echo 'ERROR: Couldn'\''t update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd with the data provided. Running diagnostics...'
ERROR: Couldn't update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd with the data provided. Running diagnostics...
+ func_debug_setup
+ echo 'Testing file permissions...'
Testing file permissions...
+ func_test_writable /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd
+ '[' -e /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd ']'
+ '[' -e /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd ']'
+ '[' -f /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd ']'
+ touch /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd
+ return 0
+ func_debug_setup_return_test 0
+ '[' 0 == 0 ']'
+ echo 'Testing file field count...'
Testing file field count...
+ func_compare_data_field_count_to_rrd_gauge_count
+ '[' -z 29:29:29:29:29:29:29:29:34:39:40:36:34:33:31:31 ']'
++ /usr/local/bin/rrdtool info /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd
++ grep -c 'type = "GAUGE"'
ERROR: mmaping file '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': Invalid argument
+ gauges_in_file=0
+ colons_from_data=:::::::::::::::
+ fields_in_data=47
+ '[' 0 == 47 ']'
+ return 0
+ func_debug_setup_return_test 0
+ '[' 0 == 0 ']'
+ echo 'Daignostics didn'\''t find anything wrong.'
Daignostics didn't find anything wrong.
+ exit 1
```

**Comment by seren** [comment]
Ok, the most recent version should fix that last error. Also, the rrd file needs to be initialized by the script, so if it's been created manually (like by "touch"ing it), the rrdtool will error out (which is what you were seeing with the second error). I've added a check and warning for that case.

**Comment by soaringswine** [comment]
Ok, deleted all files and started over with newest version, still getting errors. The way I'm doing is this to download the master zip, extract to a SMB share, then chowning to root from ssh:


```
Sampling every 300 seconds
Creating rrdtool db file: /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd
Rrdtool arguments:   DS:cpu0:GAUGE:600:0:150 DS:cpu1:GAUGE:600:0:150 DS:cpu2:GAUGE:600:0:150 DS:cpu3:GAUGE:600:0:150 DS:cpu4:GAUGE:600:0:150 DS:cpu5:GAUGE:600:0:150 DS:cpu6:GAUGE:600:0:150 DS:cpu7:GAUGE:600:0:150 DS:da0:GAUGE:600:0:100 DS:da1:GAUGE:600:0:100 DS:da2:GAUGE:600:0:100 DS:da3:GAUGE:600:0:100 DS:da4:GAUGE:600:0:100 DS:da5:GAUGE:600:0:100 DS:da6:GAUGE:600:0:100 DS:da7:GAUGE:600:0:100
/usr/local/bin/rrdtool create /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd --step 300 DS:cpu0:GAUGE:600:0:150 DS:cpu1:GAUGE:600:0:150 DS:cpu2:GAUGE:600:0:150 DS:cpu3:GAUGE:600:0:150 DS:cpu4:GAUGE:600:0:150 DS:cpu5:GAUGE:600:0:150 DS:cpu6:GAUGE:600:0:150 DS:cpu7:GAUGE:600:0:150 DS:da0:GAUGE:600:0:100 DS:da1:GAUGE:600:0:100 DS:da2:GAUGE:600:0:100 DS:da3:GAUGE:600:0:100 DS:da4:GAUGE:600:0:100 DS:da5:GAUGE:600:0:100 DS:da6:GAUGE:600:0:100 DS:da7:GAUGE:600:0:100 RRA:MAX:0.5:1:3000
ERROR: Cannot chmod temporary file!
Running script: '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-rrd-format.sh'


30:30:30:30:30:30:30:30:34:39:40:36:33:32:30:31


(running script again non-verbosely)
Data: 27:27:27:27:27:27:27:27:34:39:40:36:33:32:30:31

Updating the db: '/usr/local/bin/rrdtool update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd N:27:27:27:27:27:27:27:27:34:39:40:36:33:32:30:31'
ERROR: opening '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': No such file or directory
ERROR: Couldn't update /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd with the data provided. Running diagnostics...
Testing file permissions...
'/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd' doesn't exist
Testing file field count...
ERROR: opening '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': No such file or directory
Testing that file is a valid rrd file...
Test failed. '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd' is not a valid rrd file. You may need to delete it and run this script again
```

This is what gets emailed to me:
```
ERROR: Cannot chmod temporary file!
ERROR: opening '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': No such file or directory
ERROR: opening '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': No such file or directory
```

and
```
ERROR: opening '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': No such file or directory
ERROR: opening '/mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd': No such file or directory
```

**Comment by seren** [comment]
Hmm, it seems like rrdtool is having trouble `chmod`ing a temporary file. This could be permissions, but if you're running as root, it could also be that the filesystem is NTFS and doesn't understand unix file permissions.

Are you able to use chmod in the `/mnt/massivemac/Media/freenas-temperature-graphing-master` directory? What about in /tmp?

If you try running the command manually, what happens?
`/usr/local/bin/rrdtool create /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd --step 300 DS:cpu0:GAUGE:600:0:150 DS:cpu1:GAUGE:600:0:150 DS:cpu2:GAUGE:600:0:150 DS:cpu3:GAUGE:600:0:150 DS:cpu4:GAUGE:600:0:150 DS:cpu5:GAUGE:600:0:150 DS:cpu6:GAUGE:600:0:150 DS:cpu7:GAUGE:600:0:150 DS:da0:GAUGE:600:0:100 DS:da1:GAUGE:600:0:100 DS:da2:GAUGE:600:0:100 DS:da3:GAUGE:600:0:100 DS:da4:GAUGE:600:0:100 DS:da5:GAUGE:600:0:100 DS:da6:GAUGE:600:0:100 DS:da7:GAUGE:600:0:100 RRA:MAX:0.5:1:3000`

**Comment by seren** [comment]
Also, could you let me know the result of these commands?

`ls -lL /tmp | cut -d' ' -f 1`

`ls -lL /mnt/massivemac/Media/freenas-temperature-graphing-master | cut -d' ' -f 1`

(I'm trying to figure out a test that can detect a non-unix filesystem)

**Comment by soaringswine** [comment]
> Are you able to use chmod in the /mnt/massivemac/Media/freenas-temperature-graphing-master directory? 

chmod: /mnt/massivemac/Media/freenas-temperature-graphing-master/rrd.sh: Operation not permitted

> What about in /tmp?

Yes.

> If you try running the command manually, what happens?

/usr/local/bin/rrdtool create /mnt/massivemac/Media/freenas-temperature-graphing-master/temps-5min.rrd --step 300 DS:cpu0:GAUGE:600:0:150 DS:cpu1:GAUGE:600:0:150 DS:cpu2:GAUGE:600:0:150 DS:cpu3:GAUGE:600:0:150 DS:cpu4:GAUGE:600:0:150 DS:cpu5:GAUGE:600:0:150 DS:cpu6:GAUGE:600:0:150 DS:cpu7:GAUGE:600:0:150 DS:da0:GAUGE:600:0:100 DS:da1:GAUGE:600:0:100 DS:da2:GAUGE:600:0:100 DS:da3:GAUGE:600:0:100 DS:da4:GAUGE:600:0:100 DS:da5:GAUGE:600:0:100 DS:da6:GAUGE:600:0:100 DS:da7:GAUGE:600:0:100 RRA:MAX:0.5:1:3000
ERROR: Cannot chmod temporary file!


> ls -lL /tmp | cut -d' ' -f 1

total
drwxrwxrwt
drwxr-xr-x
-rw-r--r--
-rw-rw-r--
-rw-r--r--
-rw-rw-r--
drwxr-xr-x
-rw-r--r--
drwx------
-rw-r--r--
-rw-r--r--
-rwxrwxrwx
drwxr-xr-x
drwxr-xr-x
-rw-r--r--
-rw-r--r--
-rw-------
drwxrwxrwt

> ls -lL /mnt/massivemac/Media/freenas-temperature-graphing-master | cut -d' ' -f 1

total
drwxrwxr-x+
drwxrwxr-x+
-rwxrwxr-x+
-rwxrwxr-x+
-rwxrwxr-x+
drwxrwxr-x+
-rwxrwxr-x+
-rwxrwxr-x+
-rwxrwxr-x+
-rwxrwxr-x+


If it helps, it is a "Windows" dataset for SMB purposes, but obviously running on top of ZFS.

**Comment by seren** [comment]
Ahh, that may explain it. I don't think rrdtool will run on top of a windows dataset. I could see about having rrdtool do it's work in /tmp and then move the result to the main directory...

**Comment by soaringswine** [comment]
Ah, got it, I'll just have it run in a different dataset then try symlinking the graph pngs to the Windows dataset.

Thanks for the help!
